name: Node.js CI

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - 'feature/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:coveralls
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.REPO_TOKEN}}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
